services:
  app:
    image: ghcr.io/andyweiss/baresipui:latest
    container_name: baresip-ui
    ports:
      - 3000:3000
    environment:
      - BARESIP_HOST=baresip
      - BARESIP_PORT=4444
    depends_on:
      - baresip
    restart: unless-stopped
    volumes:
      - ./baresip/config:/config
      - ./baresip/.asoundrc:/config/.asoundrc:ro
      - shared-logs:/shared-logs
    networks:
      - baresip-network
    healthcheck:
      test:
        - CMD
        - wget
        - --spidercd 
        - -q
        - http://127.0.0.1:3000/api/health
      interval: 30s
      timeout: 10s
      retries: 3
  baresip:
    image: ghcr.io/andyweiss/baresip:latest
    container_name: baresip
    restart: unless-stopped
    init: true
    entrypoint: ["/bin/sh", "-c"]
    volumes:
      - ./baresip/config:/config
      - ./baresip/.asoundrc:/root/.asoundrc
      - shared-logs:/shared-logs
    ports:
      - 4444:4444/tcp
      - 5060:5060/udp
      - 10000-10500:10000-10500/udp
    command:
      - "/entrypoint.sh baresip -f /config 2>&1 | tee /shared-logs/baresip.log"
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    ulimits:
      rtprio: 99
      memlock: -1
    cap_add:
      - SYS_NICE
    networks:
      - baresip-network
volumes:
  shared-logs:
networks:
  baresip-network:
    driver: bridge
