# Alternative compose config to use custom-built baresip
# Usage: docker compose -f compose.build-from-source.yaml up -d

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BARESIP_HOST: baresip-custom
        BARESIP_PORT: 4444
    container_name: baresip-ui
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - BARESIP_HOST=baresip-custom
      - BARESIP_PORT=4444
    depends_on:
      - baresip-custom
    restart: unless-stopped
    volumes:
      - ./baresip/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - baresip-network
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -q
        - http://localhost:3000/api/health
      interval: 30s
      timeout: 10s
      retries: 3

  baresip-custom:
    build:
      context: ./baresip
      dockerfile: Dockerfile.build-from-source
    container_name: baresip-custom
    restart: unless-stopped
    volumes:
      - ./baresip/config:/config
      - ./baresip/.asoundrc:/root/.asoundrc
    ports:
      - 8000:8000/tcp
      - 5555:5555/tcp
      - 4444:4444/tcp
    command:
      - baresip
      - -f
      - /config
    stdin_open: true
    tty: true
    security_opt:
      - seccomp=unconfined
    devices:
      - /dev/snd:/dev/snd
      - /dev/tty:/dev/tty
    group_add:
      - audio
    ulimits:
      rtprio: 99
      memlock: -1
    cap_add:
      - SYS_NICE
    networks:
      - baresip-network

networks:
  baresip-network:
    driver: bridge
